name: "テスト"

on:
  push:
    branches:
      - main
      - v11
  pull_request:

env:
  NODE_VERSION: '16'

jobs:
  jest:
    name: Run tests with jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install packages
        run: npm install
      - name: Run Tests
        run: npm test
