name: "NPM パッケージの自動アップデート"

on:
  schedule:
    # 05:20 in UTC is 14:20 in JST.
    - cron: '20 5 * * 6'

env:
  NODE_VERSION: '16'

jobs:
  update:
    name: Create Pull Request to update packages
    runs-on: ubuntu-latest
    matrix:
      branch: [v12, v11]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Update packages
        run: npm update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
