name: "NPM パッケージの自動アップデート"

on:
  schedule:
    # 05:20 in UTC is 14:20 in JST.
    - cron: '20 5 * * 6'
  workflow_dispatch:

env:
  NODE_VERSION: '16'

jobs:
  update:
    name: Create Pull Request to update packages
    runs-on: ubuntu-latest
    matrix:
      branch: [v12, v11]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install packages
        run: npm ci
      - name: Check outdated packages
        uses: actions/github-script@v6
        with:
          script: |
            const { stdout, stderr } = exec.getExecOutput(`npm outdated`, [])
            core.setOutput('stdout', stdout)
            core.setOutput('stderr', stderr)
        id: npm_outdated
      - name: Show outdated packages in summary
        uses: actions/github-script@v6
        with:
          script: |
            const report = JSON.parse(process.env.OUTDATED_REPORT_JSON)
            const header = [
              {data: "Name", header: true},
              {data: "Current", header: true},
              {data: "Latest", header: true},
            ]
            const rows = Object.entries(report).map(([name, data]) => {
              return [name, data['current'], data['latest']]
            })
            core.summary
              .addHeading('Outdated packages :broom:')
              .addTable([header, ...rows])
              .write()
        env:
          OUTDATED_REPORT_JSON: ${{ steps.npm_outdated.outputs.stdout }}
      - name: Update packages
        run: npm update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
